name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt install luarocks -y
          sudo luarocks install luacheck

      - name: Run Luacheck
        run: luacheck lua test

  stylua:
    name: StyLua
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.0.2
          args: --check lua test

  typecheck:
    strategy:
      matrix:
        nvim_tag:
          - v0.9.4
          - v0.10.0
    name: typecheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: stevearc/nvim-typecheck-action@v2
        with:
          path: lua
          nvim-version: ${{ matrix.nvim_tag }}

  run_tests:
    strategy:
      matrix:
        nvim_tag:
          - v0.9.4
          - v0.10.0

    name: Run tests
    runs-on: ubuntu-22.04
    env:
      NVIM_TAG: ${{ matrix.nvim_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Run tests
        run: |
          bash ./run_tests.sh
